name: Build and Push AMP Docker Images

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every week
  push:
    paths:
      - 'AMPDockerfile*'
      - 'ampstart.sh'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run buildDockerBase.sh script
        run: ./buildDockerBase.sh
